.TH DOSAGE 1
.SH NAME
dosage \- a commandline webcomic downloader and archiver
.SH SYNOPSIS
\fBdosage\fP [\fIoptions\fP] \fImodule\fP...
.SH DESCRIPTION
.B dosage
is an application designed to keep a local mirror of specific
web comics and other picture\-based content, such as
\fIPicture Of The Day\fP sites, with a variety of options
for updating and maintaining collections.
.SH OPTIONS
.TP
\fB\-b\fP \fIPATH\fP, \fB\-\-basepath=\fP\fIPATH\fP
Specifies a base path to put comic subdirectories. The default is \fBComics\fP.
.TP
\fB\-\-baseurl=\fP\fIPATH\fP
Specifies the base URL for output events. The default is a local file URI.
.TP
\fB\-a\fP, \fB\-\-all\fP
Traverses all available strips backwards from the current one.
This can be useful you want a full collection of a new comic strip,
or update an existing one where files are missing.
.
Catchups can start at a specific strip by using the index syntax, see
the
.B INDEX SYNTAX
and
.B SPECIAL SYNTAX
sections for more information. This is useful when you missed some days 
and want only to download the missing files. To make this task easy,
the traversal ends at the first existing image file when starting from
an index (excluding the index itself).
.TP
\fB\-h\fP, \fB\-\-help\fP
Output brief help information.
.TP
\fB\-l\fP, \fB\-\-list\fP
List available comic modules in multi\-column fashion.
.TP
\fB\-\-singlelist\fP
List available comic modules in single-column fashion.
.TP
\fB\-m\fP \fIMODULE\fP, \fB\-\-modulehelp=\fP\fIMODULE\fP
Output module-specific help for \fIMODULE\fP.
.TP
\fB\-o\fP \fIOUTPUT\fP, \fB\-\-output=\fP\fIOUTPUT\fP
\fIOUTPUT\fP may be any one of the following:
.PP
.RS
.BR "html " \-
Writes out an HTML file linking to the strips actually downloaded in the
current run, named by date (ala dailystrips). The files can be found in the
\fBhtml\fP directory of your \fBComics\fP directory.
.RE
.PP
.RS
.BR "rss " \-
Writes out an RSS feed detailing what strips were downloaded in the last 24
hours. The feed can be found in \fBComics/dailydose.xml\fP.
.RE
.PP
.RS
.BR "rss " \-
Writes an RSS feed with all of the strips downloaded during the run, for use
with your favourite RSS aggregator.
.RE
.TP
\fB\-t\fP, \fB\-\-timestamps\fP
Print timestamps for all output at any level.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Increase the output level by one with each occurence.
.TP
\fB\-V\fP, \fB\-\-version\fP
Display the version number.
.I module
At least one valid
.I module
must be specified. A list of valid modules can be found by passing the
.B \-l
option. Multiple
.I module
arguments can be specified on the command line.
Module names are case insensitive, and it is sufficient to specify a
unique substring of the module name.
.SH INDEX SYNTAX
Instead of starting at the latest comic strip, an index lets dosage start
at a certain strip. The index can be specified by appending a colon \fB:\fP
and the index name after the module. Multiple comma-spearated indices can
also be specified.
.PP
The index name itself usually is the part of the comic strip URL that identifiess
a strip, eg. a number or a date. The expected format is documented when using
the \fB\-\-modulehelp\fP option.
.SH SPECIAL SYNTAX
.TP
.B @
This expands to mean all the comics currently in your \fBComics\fP
directory. All other specified comic module names will be ignored.
.TP
.B @@
This expands to mean all the comics available to Dosage.
.PP
\fBINDEX SYNTAX\fP can not be used with \fBSPECIAL SYNTAX\fP.
.SH EXAMPLES
Retrieve all Mega Tokyo comics:
.RS
.B dosage \-a megatokyo
.RE
.PP
Retrieve the current comic of Cyanide and Happiness:
.RS
.B dosage cyanideandhappiness
.RE
.PP
Retrieve the current strip of all comics in your \fBComics\fP directory:
.RS
.B dosage @
.RE
.PP
Retrieve the current strip of every comic that there is a module for:
.RS
.B dosage @@
.RE
.PP
Retrieve the Penny Arcade strip for a given index:
.RS
.B dosage pennyarcade:2004\-07\-22
.RE
Retrieve Calvin and Hobbes strips from a given index going backwards to
the beginning until an existing file is found:
.RS
.B dosage \-c calvinandhobbes:20120722
.RE
.SH ENVIRONMENT
.IP HTTP_PROXY
.B mainline
will use the specified HTTP proxy when downloading URL contents.
.SH NOTES
Should retrieval fail on any given strip
.B mainline
will attempt to retry. However the retry information is only outputted
in the
.B second
and successive output levels.
.PP
At the time of writing, a
.B complete
Dosage collection weighs in at around 3.0GB.
.SH RETURN VALUE
The return value greater than zero when
.IP \(bu
a program error occurred.
.IP \(bu
comics could not be found or downloaded
.IP \(bu
the program run was aborted with Ctrl-C
.PP
Else the return value is zero.
.SH BUGS
Users can report or view bugs, patches or feature suggestions at
.I https://github.com/wummel/dosage/issues
.SH AUTHORS
Jonathan Jacobs <korpse@slipgate.za.net>
.br
Tristan Seligmann <mithrandi@slipgate.za.net>
.br
Bastian Kleineidam <calvin@users.sourceforge.net>
.SH COPYRIGHT
Copyright \(co 2004-2005 Tristan Seligmann and Jonathan Jacobs
.br
Copyright \(co 2012 Bastian Kleineidam
