# -*- coding: utf-8 -*-
# ISO 693-1 language codes from pycountry
# This file is automatically generated, DO NOT EDIT!
Languages = {
    'de': u'German',
    'en': u'English',
    'es': u'Spanish; Castilian',
    'fi': u'Finnish',
    'fr': u'French',
}
