# -*- coding: utf-8 -*-
# ISO 693-1 language codes from pycountry
# This file is automatically generated, DO NOT EDIT!
from __future__ import absolute_import, division, print_function
Languages = {
    'de': 'German',
    'en': 'English',
    'es': 'Spanish',
    'fi': 'Finnish',
    'fr': 'French',
    'it': 'Italian',
    'ja': 'Japanese',
    'pt': 'Portuguese',
}
