#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2004 Tristan Seligmann and Jonathan Jacobs
# SPDX-FileCopyrightText: © 2012 Bastian Kleineidam
# SPDX-FileCopyrightText: © 2015 Tobias Gruetzmacher
'''update languages.py from pycountry'''
import codecs
import os

from dosagelib.scraper import scrapers


def main():
    """Update language information in dosagelib/languages.py."""
    basepath = os.path.dirname(os.path.dirname(__file__))
    fn = os.path.join(basepath, 'dosagelib', 'languages.py')
    with codecs.open(fn, 'w', 'utf-8') as f:
        f.write('# SPDX-License-Identifier: MIT\n')
        f.write('# ISO 693-1 language codes from pycountry\n')
        f.write('# This file is automatically generated, DO NOT EDIT!\n')
        lang = get_used_languages()
        write_languages(f, lang)


def get_used_languages():
    languages = {}
    for scraperobj in scrapers.get():
        lang = scraperobj.lang
        if lang not in languages:
            languages[lang] = scraperobj.language()
    return languages


def write_languages(f, langs):
    """Write language information."""
    f.write("Languages = {%s" % os.linesep)
    for lang in sorted(langs):
        f.write(f"    {lang!r}: {langs[lang]!r},{os.linesep}")
    f.write("}%s" % os.linesep)


if __name__ == '__main__':
    main()
